name: Multi-Stage Docker Publish

on:
  push:
    branches:
      - main
      - dev_tharindu
      - dev/pabasara
      - dev-malshi
      - dev-geyumi
  workflow_dispatch:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run tests
      - name: Run tests
        run: ./gradlew clean test

      # Build JAR (bootJar only)
      - name: Build JAR
        run: ./gradlew bootJar

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set Docker image tags
      - name: Set image tags
        id: vars
        run: |
          USER=${{ secrets.DOCKERHUB_USERNAME }}
          APP_NAME=ets_server
          REPO=$USER/${APP_NAME}
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "TAGS=$REPO:latest,$REPO:main" >> $GITHUB_OUTPUT
          else
            BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
            echo "TAGS=$REPO:$BRANCH" >> $GITHUB_OUTPUT
          fi

      # Build & Push Docker image (multi-stage)
      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
